version: "3.9"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  bookapp:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
